allow shell to display qr code if apps don't do their own display
OpenVoiceOS/ovos-PHAL-plugin-oauth pull request #2
Opened 2023-01-20 06:38 UTC by AIIX

- Allow shell to display QR code once it is generated for skills, apps and plugins that do not have their own QML UI and are part of other frameworks, example OCP skills
- Skills, Apps can simply mark shell_integration as true during registration and once the QR is generated it will be displayed then by the shell

2023-01-20 06:40 UTC, JarbasAl commented on ovos_PHAL_plugin_oauth/__init__.py
> +        shell_display = message.data.get("shell_integration", False)
i think this should default to True

2023-01-20 06:41 UTC, JarbasAl commented on ovos_PHAL_plugin_oauth/__init__.py
> +        display_code_on_shell = data.get("shell_integration")
value should never be missing here i think, but should also default to True if somehow we get in this handler and the key is missing from data

2023-01-20 06:53 UTC, JarbasAl approved these changes

2023-01-20 06:54 UTC, JarbasAl commented on README.md
> +        "shell_integration": False #Optional - mark as false if app/skill handles displaying generated QR code. mark as true if shell should handle it.
needs updating to reflect new default

2023-01-20 08:47 UTC, AIIX commented
Also requires: https://github.com/OpenVoiceOS/ovos-backend-client/pull/25

2023-01-20 13:57 UTC, JarbasAl commented
> Also requires: [OpenVoiceOS/ovos-backend-client#25](https://github.com/OpenVoiceOS/ovos-backend-client/pull/25)

need to pin min version in requirements

2023-01-20 19:15 UTC, NeonDaniel requested changes
Needs to spec ovos-backend-client>=0.0.6a11 in requirements

2023-01-21 02:17 UTC, AIIX commented
Requirements have been fixed

2023-01-23 19:12 UTC, NeonDaniel approved these changes

2023-01-24 04:01 UTC, merged